/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicianRouteImport } from './routes/technician'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GovernorRouteImport } from './routes/governor'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as IndexRouteImport } from './routes/index'

const TechnicianRoute = TechnicianRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernorRoute = GovernorRouteImport.update({
  id: '/governor',
  path: '/governor',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/governor': typeof GovernorRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/register': typeof RegisterRoute
  '/technician': typeof TechnicianRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/governor': typeof GovernorRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/register': typeof RegisterRoute
  '/technician': typeof TechnicianRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/governor': typeof GovernorRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/register': typeof RegisterRoute
  '/technician': typeof TechnicianRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen'
    | '/governor'
    | '/login'
    | '/manager'
    | '/register'
    | '/technician'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citizen'
    | '/governor'
    | '/login'
    | '/manager'
    | '/register'
    | '/technician'
  id:
    | '__root__'
    | '/'
    | '/citizen'
    | '/governor'
    | '/login'
    | '/manager'
    | '/register'
    | '/technician'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenRoute: typeof CitizenRoute
  GovernorRoute: typeof GovernorRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  RegisterRoute: typeof RegisterRoute
  TechnicianRoute: typeof TechnicianRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technician': {
      id: '/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof TechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governor': {
      id: '/governor'
      path: '/governor'
      fullPath: '/governor'
      preLoaderRoute: typeof GovernorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenRoute: CitizenRoute,
  GovernorRoute: GovernorRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  RegisterRoute: RegisterRoute,
  TechnicianRoute: TechnicianRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
